try{
    a;

}catch (err){
    console.log(err.message + " " + err.name + " " + err.stack);
}